# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "png-js-1.0.0" = {
      name = "png-js";
      packageName = "png-js";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/png-js/-/png-js-1.0.0.tgz";
        sha512 = "k+YsbhpA9e+EFfKjTCH3VW6aoKlyNYI6NYdTfDL4CIvFnvsuO84ttonmZE7rc+v23SLTH8XX+5w/Ak9v0xGY4g==";
      };
    };
    "xhr2-0.2.1" = {
      name = "xhr2";
      packageName = "xhr2";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xhr2/-/xhr2-0.2.1.tgz";
        sha512 = "sID0rrVCqkVNUn8t6xuv9+6FViXjUVXq8H5rWOH2rz9fDNQEd4g0EA2XlcEdJXRz5BMEn4O1pJFdT+z4YHhoWw==";
      };
    };
  };
  args = {
    name = "cli";
    packageName = "cli";
    version = "1.0.0";
    src = ./..;
    dependencies = [
      sources."png-js-1.0.0"
      sources."xhr2-0.2.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
